services:
  - type: web
    name: udjk-platform
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn udjkplatform.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: SITE_URL
        sync: false

databases:
  - name: udjk-db
    databaseName: udjk_db
    user: udjk_user