# Generated by Django 6.0.2 on 2026-08-07 20:48

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/blog/')),
                ('categorie', models.CharField(choices=[('éducation', 'Éducation'), ('santé', 'Santé'), ('environement', 'Énvironement'), ('culturel', 'Culturel')], default='Éducatif', max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='albums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/albums/images/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='static/albums/videos/')),
                ('category', models.CharField(choices=[('evenement', 'Événement'), ('projet', 'Projet'), ('video', 'Vidéo'), ('reunion', 'Réunion'), ('autre', 'Autre'), ('formation', 'Formation'), ('conference', 'Conférence')], default='evenement', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_bureau', models.CharField(choices=[('EXECUTIF', 'Bureau Exécutif'), ('LOGISTIQUE', 'Bureau Logistique'), ('SUIVI_EVALUATION', 'Bureau Suivi-évaluation'), ('EDUCATIF', 'Bureau Educatif'), ('SANTE', 'Bureau Santé'), ('CULTUREL', 'Bureau Culturel'), ('ENVIRONNEMENT', 'Bureau Environnement')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('date_creation', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Bureau',
                'verbose_name_plural': 'Bureaux',
                'ordering': ['type_bureau'],
            },
        ),
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Caisse UJK', max_length=100)),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('est_principale', models.BooleanField(default=False, help_text="Caisse utilisée par défaut quand aucune n'est précisée (une seule à la fois)")),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom ')),
                ('prenom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Prénom ')),
                ('adresse', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresse ')),
                ('image', models.ImageField(upload_to='static/image/ ')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse .....@gmail.com ')),
                ('contenu', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True)),
                ('prenom', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='temoin')),
                ('genre', models.CharField(choices=[('M', 'm'), ('F', 'f')], default='M', max_length=50)),
                ('contenue', models.TextField()),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categorie', models.CharField(choices=[('fonctionnement', 'Fonctionnement'), ('projet', 'Projet'), ('evenement', 'Événement'), ('materiel', 'Matériel'), ('autre', 'Autre')], default='fonctionnement', max_length=20)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='comptabilite/justificatifs/')),
                ('date_depense', models.DateField(default=django.utils.timezone.now)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('autorise_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_autorisees', to=settings.AUTH_USER_MODEL)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='core.caisse')),
            ],
            options={
                'ordering': ['-date_depense'],
            },
        ),
        migrations.CreateModel(
            name='FicheControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('solde_theorique', models.DecimalField(decimal_places=2, max_digits=14)),
                ('solde_reel_constate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ecart', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('statut', models.CharField(choices=[('conforme', 'Conforme'), ('ecart', 'Écart constaté'), ('en_cours', 'En cours de vérification')], default='en_cours', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('date_controle', models.DateTimeField(auto_now_add=True)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_controle', to='core.caisse')),
                ('controleur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_controle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='messages_fichiers/')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('envoyeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='MessageBureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='bureaux/messages/')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_bureau', to=settings.AUTH_USER_MODEL)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.bureau')),
            ],
            options={
                'verbose_name': 'Message de Bureau',
                'verbose_name_plural': 'Messages de Bureau',
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=10)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('mois', models.DateField(default=django.utils.timezone.now, verbose_name='Mois concerné')),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('retard', 'En retard')], default='en_attente', max_length=20)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('caisse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotisations', to='core.caisse')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'ordering': ['-mois'],
                'unique_together': {('utilisateur', 'mois')},
            },
        ),
        migrations.CreateModel(
            name='JournalCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('libelle', models.CharField(max_length=200)),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='core.caisse')),
                ('depense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='core.depense')),
                ('cotisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='core.payment')),
            ],
            options={
                'ordering': ['-date_operation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriquePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('utilisateur_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_paiement', to=settings.AUTH_USER_MODEL)),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='core.payment')),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin_prevue', models.DateField(blank=True, null=True)),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('suspendu', 'Suspendu')], default='planifie', max_length=20)),
                ('budget_prevu', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('beneficiaires_directs', models.PositiveIntegerField(default=0)),
                ('beneficiaires_indirects', models.PositiveIntegerField(default=0)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_responsable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='depense',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='core.projet'),
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre ')),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications/images/', verbose_name='Image ')),
                ('video', models.FileField(blank=True, null=True, upload_to='publications/videos/', verbose_name='Vidéo ')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Publications', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date_com', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commentaires', to='core.publication')),
            ],
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reunion', models.DateField(verbose_name='Date')),
                ('lieu', models.CharField(max_length=200, verbose_name='Lieu')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('tenue', 'Tenue'), ('annulee', 'Annulée'), ('reportee', 'Reportée')], default='planifiee', max_length=20)),
                ('ordre_du_jour', models.TextField(verbose_name='Ordre du jour')),
                ('decisions_prises', models.TextField(blank=True, verbose_name='Décisions prises')),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='reunions', to=settings.AUTH_USER_MODEL)),
                ('responsable_cr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunions_compte_rendu', to=settings.AUTH_USER_MODEL, verbose_name='Responsable du CR')),
            ],
            options={
                'ordering': ['-date_reunion'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='profiles/')),
                ('adresse', models.CharField(default='Kakony', max_length=100)),
                ('profil_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('en_ligne', models.BooleanField(default=False)),
                ('derniere_activite', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_like', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.publication')),
            ],
            options={
                'unique_together': {('publication', 'utilisateur')},
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(help_text='Ex: Président, Vice-Président, Secrétaire Général, Conseiller, Directeur, Membre...', max_length=100)),
                ('est_responsable', models.BooleanField(default=False, help_text="Poste de responsable du bureau (donne le droit d'affecter des membres si le bureau est Logistique ou Exécutif)")),
                ('actif', models.BooleanField(default=True)),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
                ('affecte_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_realisees', to=settings.AUTH_USER_MODEL)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='core.bureau')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='core.utilisateur')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'ordering': ['-date_affectation'],
                'unique_together': {('membre', 'bureau', 'poste')},
            },
        ),
    ]
