# Generated by Django 5.2.4 on 2025-10-15 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom ')),
                ('prenom', models.CharField(blank=True, max_length=200, null=True, verbose_name='Prénom ')),
                ('adresse', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresse ')),
                ('image', models.ImageField(upload_to='static/image/ ')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse .....@gmail.com ')),
                ('contenu', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='adresse',
            field=models.CharField(default='Kakony', max_length=100),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='badge_png',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='numero',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='image',
            field=models.ImageField(upload_to='profiles/'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='messages_fichiers/')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('envoyeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre ')),
                ('contenu', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='publications/images/', verbose_name='Image ')),
                ('video', models.FileField(blank=True, null=True, upload_to='publications/videos/', verbose_name='Vidéo ')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Publications', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date_com', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commentaires', to='core.publication')),
            ],
        ),
        migrations.CreateModel(
            name='Bureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom complet du bureau que vous voullez créez', max_length=200, verbose_name='Nom du bureau')),
                ('sigle', models.CharField(help_text='Code unique (ex: BPK, CEK, CSK, CAK)', max_length=15, unique=True, verbose_name='Sigle')),
                ('type_bureau', models.CharField(choices=[('PRINCIPAL', 'Bureau Principal'), ('EDUCATION', 'Comité Éducation & Formation'), ('SANTE', 'Comité Santé & Hygiène'), ('AGRICULTURE', 'Comité Agriculture & Élevage'), ('INFRASTRUCTURES', 'Comité Infrastructures'), ('JEUNESSE', 'Comité Jeunesse & Sport'), ('FEMMES', 'Comité des Femmes'), ('ENVIRONNEMENT', 'Comité Environnement'), ('CULTURE', 'Comité Culture & Tradition'), ('QUARTIER', 'Groupe de Quartier'), ('VILLAGE', 'Groupe de Village'), ('PROJET', 'Comité de Projet Spécifique')], default='UDJK', max_length=20, verbose_name='Type de structure')),
                ('mission', models.TextField(help_text='Description de la mission et des objectifs du bureau/comité', verbose_name='Mission et objectifs')),
                ('zone_intervention', models.CharField(choices=[('KAKONY_CENTRE', 'Kakony Centre'), ('QUARTIER_MOSQUE', 'Quartier Mosquée'), ('QUARTIER_MARCHE', 'Quartier Marché'), ('QUARTIER_ECOLE', 'Quartier École'), ('VILLAGES_PERIPHERIE', 'Villages Périphérie'), ('ZONE_AGRICOLE', 'Zone Agricole'), ('DIVERTISSEMENT', 'divertissement'), ('ENSEMBLE_COMMUNE', 'Ensemble de la Commune')], default='ENSEMBLE_COMMUNE', max_length=30, verbose_name="Zone d'intervention")),
                ('adresse_locale', models.CharField(blank=True, help_text='Lieu précis à Kakony (ex: Près de la mosquée centrale, Marché de Kakony)', max_length=200, verbose_name='Adresse locale')),
                ('date_creation', models.DateField(help_text='Date de création du bureau/comité', verbose_name='Date de création')),
                ('date_derniere_assemblee', models.DateField(blank=True, help_text='Date de la dernière assemblée générale', null=True, verbose_name='Dernière assemblée')),
                ('frequence_reunions', models.CharField(default='Mensuelle', help_text='Ex: Hebdomadaire, Mensuelle, Trimestrielle', max_length=50, verbose_name='Fréquence des réunions')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('EN_PROJET', 'En Projet'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=15, verbose_name='Statut')),
                ('niveau_hierarchique', models.PositiveIntegerField(default=0, editable=False, verbose_name='Niveau hiérarchique')),
                ('telephone_contact', models.CharField(blank=True, max_length=20, verbose_name='Téléphone de contact')),
                ('email_contact', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact')),
                ('taux_reussite', models.DecimalField(blank=True, decimal_places=2, help_text='Pourcentage de projets menés à bien', max_digits=5, null=True, verbose_name='Taux de réussite (%)')),
                ('animateur_communautaire', models.ForeignKey(blank=True, help_text='Personne chargée de la mobilisation communautaire', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bureaux_animateur_kakony', to=settings.AUTH_USER_MODEL, verbose_name='Animateur Communautaire')),
                ('benevoles', models.ManyToManyField(blank=True, related_name='bureaux_benevole_kakony', to=settings.AUTH_USER_MODEL, verbose_name='Bénévoles')),
                ('bureau_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='structures_filiales', to='core.bureau', verbose_name='Structure de rattachement')),
                ('membres_actifs', models.ManyToManyField(blank=True, help_text='Membres participant régulièrement aux activités', related_name='bureaux_membre_actif_kakony', to=settings.AUTH_USER_MODEL, verbose_name='Membres actifs')),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bureaux_presides_kakony', to=settings.AUTH_USER_MODEL, verbose_name='Président(e)')),
                ('responsable_technique', models.ForeignKey(blank=True, help_text='Expert ou technicien spécialisé dans le domaine', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bureaux_technique_kakony', to=settings.AUTH_USER_MODEL, verbose_name='Responsable Technique')),
                ('secretaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bureaux_secretaire_kakony', to=settings.AUTH_USER_MODEL, verbose_name='Secrétaire')),
                ('secretaire_adjoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bureaux_secretaire_adjoint_kakony', to=settings.AUTH_USER_MODEL, verbose_name='Secrétaire Adjoint(e)')),
                ('tresorier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bureaux_tresorier_kakony', to=settings.AUTH_USER_MODEL, verbose_name='Trésorier(ère)')),
                ('vice_president', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bureaux_vice_president_kakony', to=settings.AUTH_USER_MODEL, verbose_name='Vice-président(e)')),
            ],
            options={
                'verbose_name': 'Bureau',
                'verbose_name_plural': 'Bureaux',
                'ordering': ['niveau_hierarchique', 'type_bureau', 'nom'],
                'permissions': [('export_bureaux', 'Peut exporter les données des bureaux'), ('gerer_tous_bureaux', 'Peut gérer tous les bureaux sans restriction')],
                'unique_together': {('nom', 'zone_intervention')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, default='10000.00', max_digits=10, verbose_name='Montant')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('mois', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('paye', 'Payé'), ('retard', 'En retard')], default='en_attente', max_length=20)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cotisation',
                'verbose_name_plural': 'Cotisations',
                'ordering': ['-mois'],
                'unique_together': {('utilisateur', 'mois')},
            },
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_like', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='core.publication')),
            ],
            options={
                'unique_together': {('publication', 'utilisateur')},
            },
        ),
    ]
