# Generated by Django 6.0.2 on 2026-04-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contact_utilisateur_adresse_utilisateur_badge_png_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bureau',
            name='secretaire_adjoint',
        ),
        migrations.AddField(
            model_name='actualite',
            name='categorie',
            field=models.CharField(choices=[('éducation', 'Éducation'), ('santé', 'Santé'), ('environement', 'Énvironement'), ('culturel', 'Culturel')], default='Éducatif', max_length=250),
        ),
        migrations.AddField(
            model_name='publication',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='adresse_locale',
            field=models.CharField(blank=True, help_text='Lieu précis à Kakony', max_length=200, verbose_name='Adresse locale'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='type_bureau',
            field=models.CharField(choices=[('PRINCIPAL', 'Bureau Principal'), ('EDUCATION', 'Comité Éducation & Formation'), ('SANTE', 'Comité Santé & Hygiène'), ('JEUNESSE', 'Comité Jeunesse & Sport'), ('FEMMES', 'Comité des Femmes'), ('ENVIRONNEMENT', 'Comité Environnement'), ('CULTURE', 'Comité Culture & Tradition')], default='UDJK', max_length=20, verbose_name='Type de structure'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='zone_intervention',
            field=models.CharField(choices=[('KAKONY_CENTRE', 'Kakony Centre'), ('Village', 'Village')], default='ENSEMBLE_COMMUNE', max_length=30, verbose_name="Zone d'intervention"),
        ),
    ]
