# Generated by Django 6.0.2 on 2026-05-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_bureau_secretaire_adjoint_actualite_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True)),
                ('prenom', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='temoin')),
                ('genre', models.CharField(choices=[('M', 'm'), ('F', 'f')], default='M', max_length=50)),
                ('contenue', models.TextField()),
                ('date_creation', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
