# Generated by Django 6.0.2 on 2026-08-04 21:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_temoin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Caisse UJK', max_length=100)),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('date_maj', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='bureau',
            options={'ordering': ['type_bureau'], 'verbose_name': 'Bureau', 'verbose_name_plural': 'Bureaux'},
        ),
        migrations.AlterUniqueTogether(
            name='bureau',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='badge_png',
        ),
        migrations.AddField(
            model_name='bureau',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='date_paiement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='derniere_activite',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='en_ligne',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='profil_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/qr/'),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='date_creation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='nom',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bureau',
            name='type_bureau',
            field=models.CharField(choices=[('EXECUTIF', 'Bureau Exécutif'), ('LOGISTIQUE', 'Bureau Logistique'), ('SUIVI_EVALUATION', 'Bureau Suivi-évaluation'), ('EDUCATIF', 'Bureau Educatif'), ('SANTE', 'Bureau Santé'), ('CULTUREL', 'Bureau Culturel'), ('ENVIRONNEMENT', 'Bureau Environnement')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mois',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Mois concerné'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='caisse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotisations', to='core.caisse'),
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categorie', models.CharField(choices=[('fonctionnement', 'Fonctionnement'), ('projet', 'Projet'), ('evenement', 'Événement'), ('materiel', 'Matériel'), ('autre', 'Autre')], default='fonctionnement', max_length=20)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='comptabilite/justificatifs/')),
                ('date_depense', models.DateField(default=django.utils.timezone.now)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('autorise_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses_autorisees', to=settings.AUTH_USER_MODEL)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses', to='core.caisse')),
            ],
            options={
                'ordering': ['-date_depense'],
            },
        ),
        migrations.CreateModel(
            name='FicheControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periode_debut', models.DateField()),
                ('periode_fin', models.DateField()),
                ('solde_theorique', models.DecimalField(decimal_places=2, max_digits=14)),
                ('solde_reel_constate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('ecart', models.DecimalField(decimal_places=2, default=Decimal('0'), editable=False, max_digits=14)),
                ('statut', models.CharField(choices=[('conforme', 'Conforme'), ('ecart', 'Écart constaté'), ('en_cours', 'En cours de vérification')], default='en_cours', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('date_controle', models.DateTimeField(auto_now_add=True)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fiches_controle', to='core.caisse')),
                ('controleur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_controle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoriquePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('cotisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='core.payment')),
                ('utilisateur_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_paiement', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
        migrations.CreateModel(
            name='JournalCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('entree', 'Entrée'), ('sortie', 'Sortie')], max_length=10)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('libelle', models.CharField(max_length=200)),
                ('date_operation', models.DateTimeField(auto_now_add=True)),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='core.caisse')),
                ('cotisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='core.payment')),
                ('depense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='core.depense')),
            ],
            options={
                'ordering': ['-date_operation'],
            },
        ),
        migrations.CreateModel(
            name='MessageBureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='bureaux/messages/')),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_bureau', to=settings.AUTH_USER_MODEL)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.bureau')),
            ],
            options={
                'verbose_name': 'Message de Bureau',
                'verbose_name_plural': 'Messages de Bureau',
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date_debut', models.DateField()),
                ('date_fin_prevue', models.DateField(blank=True, null=True)),
                ('date_fin_reelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('en_cours', 'En cours'), ('termine', 'Terminé'), ('suspendu', 'Suspendu')], default='planifie', max_length=20)),
                ('budget_prevu', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('beneficiaires_directs', models.PositiveIntegerField(default=0)),
                ('beneficiaires_indirects', models.PositiveIntegerField(default=0)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projets_responsable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='depense',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='core.projet'),
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reunion', models.DateField(verbose_name='Date')),
                ('lieu', models.CharField(max_length=200, verbose_name='Lieu')),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiée'), ('tenue', 'Tenue'), ('annulee', 'Annulée'), ('reportee', 'Reportée')], default='planifiee', max_length=20)),
                ('ordre_du_jour', models.TextField(verbose_name='Ordre du jour')),
                ('decisions_prises', models.TextField(blank=True, verbose_name='Décisions prises')),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='reunions', to=settings.AUTH_USER_MODEL)),
                ('responsable_cr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reunions_compte_rendu', to=settings.AUTH_USER_MODEL, verbose_name='Responsable du CR')),
            ],
            options={
                'ordering': ['-date_reunion'],
            },
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='adresse_locale',
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='animateur_communautaire',
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='benevoles',
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='bureau_parent',
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='date_derniere_assemblee',
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='date_modification',
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='email_contact',
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='frequence_reunions',
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='membres_actifs',
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='niveau_hierarchique',
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='president',
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='responsable_technique',
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='secretaire',
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='sigle',
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='taux_reussite',
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='telephone_contact',
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='tresorier',
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='vice_president',
        ),
        migrations.RemoveField(
            model_name='bureau',
            name='zone_intervention',
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(help_text='Ex: Président, Vice-Président, Secrétaire Général, Conseiller, Directeur, Membre...', max_length=100)),
                ('est_responsable', models.BooleanField(default=False, help_text="Poste de responsable du bureau (donne le droit d'affecter des membres si le bureau est Logistique ou Exécutif)")),
                ('actif', models.BooleanField(default=True)),
                ('date_affectation', models.DateTimeField(auto_now_add=True)),
                ('affecte_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affectations_realisees', to=settings.AUTH_USER_MODEL)),
                ('bureau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='core.bureau')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='core.utilisateur')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'ordering': ['-date_affectation'],
                'unique_together': {('membre', 'bureau', 'poste')},
            },
        ),
    ]
