# Generated by Django 6.0.2 on 2026-08-05 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_affectation_membre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='membre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='core.utilisateur'),
        ),
    ]
