# Generated by Django 6.0.2 on 2026-08-06 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_affectation_membre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='qr_code',
        ),
    ]
