# Generated by Django 6.0.2 on 2026-08-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_utilisateur_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='caisse',
            name='est_principale',
            field=models.BooleanField(default=False, help_text="Caisse utilisée par défaut quand aucune n'est précisée (une seule à la fois)"),
        ),
    ]
